### ISSUE TITLE
metadata.rb missing

### ISSUE THREAD

**Issue by fcecagno** [opscode-cookbooks/apt#116]
Hi guys, I'm unable to install version 2.6.1 because metadata.rb is missing, see: https://supermarket.chef.io/cookbooks/apt/versions/2.6.1#foodcritic

**Comment by someara** [comment]
Hi.

So, what's happening here is cookbook artifacts are being uploaded with newer version of stove, which only installs fully compiled metadata.

https://github.com/sethvargo/stove/blob/master/CHANGELOG.md#v323-2014-10-12

This "broke the world" for people using "knife cookbook site install", which we've fixed in Chef 12, and are currently back-porting to Chef 11. 

The fix is in the pipeline https://github.com/opscode/chef/pull/2345

And will be released in 11.18.0.

-s

**Comment by fcecagno** [comment]
Thanks for the update @someara, and thanks for the effort to backport it to Chef 11.
